apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: NotificationService
    app.kubernetes.io/name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
      app.kubernetes.io/name: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        app.kubernetes.io/name: notification-service
    spec:
      containers:
      - name: notification-service
        image: mjjos1/notification-service:0.9.3
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: gmail-service
          mountPath: "/etc/creds"
          readOnly: true
        - name: gmail-client
          mountPath: "/etc/creds"
          readOnly: true
      volumes:
      - name: gmail-service
        secret:
          secretName: gmail-service-secret
          optional: false
      - name: gmail-client
        secret:
          secretName: gmail-service-client
          optional: false